resolver: lts-15.16
extra-deps:
  - git: https://github.com/juhp/http-query.git
    commit: 95bfbbfde4c1ea1862fc4ed03bd5f0635253486e
  - git: https://github.com/juhp/pdc-hs.git
    commit: c8747e722616407a987322bef9a299328a3fde55
