resolver: lts-15.16
extra-deps:
  - git: https://github.com/juhp/http-query.git
    commit: 95bfbbfde4c1ea1862fc4ed03bd5f0635253486e
  - git: https://github.com/juhp/pdc-hs.git
    commit: d87a136336b68d30a02694783f7607fb17e9f97b
